{
 "title": "Alertmanager",
 "description": "Updated dashboard for Alertamanager",
 "tags": [
  "Alert manager",
  "Alerts"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasrouce", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(alertmanager_build_info,instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of instances",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "count(alertmanager_build_info)" }
   ]
  },
  {
   "title": "Instance versions and up time",
   "type": "table",
   "description": "Table containing list of Alertmanager instances showing it's version, up time, last reload time and if it was successful.",
   "gridPos": { "h": 5, "w": 9, "x": 3, "y": 1 },
   "targets": [
    { "expr": "alertmanager_build_info" },
    {
     "expr": "time()-alertmanager_config_last_reload_success_timestamp_seconds"
    },
    {
     "expr": "alertmanager_config_last_reload_successful"
    }
   ]
  },
  {
   "title": "Cluster size",
   "type": "stat",
   "description": "Number of peers in the Alertmanager cluster.",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "alertmanager_cluster_members{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Number of active alerts",
   "type": "stat",
   "description": "Current number of active alerts.",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "alertmanager_alerts{state=\"active\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Number of suppressed alerts",
   "type": "stat",
   "description": "Current number of suppressed alerts.",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "alertmanager_alerts{state=\"suppressed\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Number of active silences",
   "type": "stat",
   "description": "Current number of active silences.",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "alertmanager_silences{state=\"active\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Notifications",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Notifications sent from $instance",
     "type": "timeseries",
     "description": "Number of sent notifications to distinct integrations such as PagerDuty, Slack and so on. On negative axis are displayed failed notifications.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(alertmanager_notifications_total{instance=~\"$instance\"}[$__rate_interval])) by (integration)",
       "legendFormat": "{{ integration}}"
      },
      {
       "expr": "sum(increase(alertmanager_notifications_failed_total{instance=~\"$instance\"}[$__rate_interval])) by (integration)",
       "legendFormat": "Failed {{ integration }}"
      }
     ]
    },
    {
     "title": "Notification durations per integration on $instance",
     "type": "timeseries",
     "description": "Duration of notification sends in 0.99 and 0.9 quantiles per integration.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(histogram_quantile(0.9,rate(alertmanager_notification_latency_seconds_bucket{instance=~\"$instance\"}[$__rate_interval]))) by (integration)",
       "legendFormat": "0.9q {{ integration }}"
      },
      {
       "expr": "sum(histogram_quantile(0.99,rate(alertmanager_notification_latency_seconds_bucket{instance=~\"$instance\"}[$__rate_interval]))) by (integration)",
       "legendFormat": "0.99q  {{ integration }}"
      }
     ]
    },
    {
     "title": "Silences GC duraton on $instance",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "increase(alertmanager_silences_gc_duration_seconds_sum{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "Silecnces GC  duration"
      }
     ]
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active alerts in $instance",
     "type": "timeseries",
     "description": "Number of alerts by state such as `active`, `suppressed` etc.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(alertmanager_alerts{instance=~\"$instance\"}) by (state)",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "Received alerts by status for $instance",
     "type": "timeseries",
     "description": "Number of received alerts from Prometheus by status `firing` on positive axis and `resolved` on negative axis.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(alertmanager_alerts_received_total{instance=~\"$instance\"}[$__rate_interval])) by (status)",
       "legendFormat": "{{ status }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Silences",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Silences count by state on $instance",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "alertmanager_silences{instance=~\"$instance\"}",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "Silences query count on $instance",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(alertmanager_silences_queries_total{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "Silecnces query count"
      },
      {
       "expr": "increase(alertmanager_silences_query_errors_total{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "Silecnces query fails"
      }
     ]
    },
    {
     "title": "Silences query duration on $instance",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 21 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(1,rate(alertmanager_silences_query_duration_seconds_bucket{instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "Silecnces query duration"
      }
     ]
    },
    {
     "title": "Silences snapshot size on $instance",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 27 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "alertmanager_silences_snapshot_size_bytes{instance=~\"$instance\"}",
       "legendFormat": "Silecnces snapshot size"
      }
     ]
    },
    {
     "title": "Silences snapshot duration on $instance",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 33 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "increase(alertmanager_silences_snapshot_duration_seconds_sum{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "Silecnces snapshot duration"
      }
     ]
    }
   ]
  },
  {
   "title": "Cluster members",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Clusterhealth score for $instance",
     "type": "timeseries",
     "description": "Shows cluster score representing cluster health. From Hashicorps official documentation: \n> This metric describes a node's perception of its own health based on how well it is meeting the soft real-time requirements of the protocol. This metric ranges from 0 to 8, where 0 indicates \"totally healthy\".\n\nFor more info see https://www.consul.io/docs/agent/telemetry.html#cluster-health",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "alertmanager_cluster_health_score{instance=~\"$instance\"}",
       "legendFormat": "Cluster health score"
      }
     ]
    },
    {
     "title": "Cluster members count on $instance",
     "type": "timeseries",
     "description": "Shows gossip cluster members count in time and failing peers in case of any in red color.",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 25 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "alertmanager_cluster_members{instance=~\"$instance\"}",
       "legendFormat": "Number of cluster members"
      },
      {
       "expr": "alertmanager_cluster_failed_peers{instance=~\"$instance\"}",
       "legendFormat": "Number of failed peers"
      }
     ]
    },
    {
     "title": "Cluster peers left/joined on $instance",
     "type": "timeseries",
     "description": "On positive axis shows number of peers that joined the cluster and on negative axis number of peers that left the cluster.",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 40 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(alertmanager_cluster_peers_left_total{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "Cluster joined peers"
      },
      {
       "expr": "increase(alertmanager_cluster_peers_joined_total{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "Cluster left peers"
      }
     ]
    },
    {
     "title": "Cluster reconnections on $instance",
     "type": "timeseries",
     "description": "On positive axis is number of attempts to reconnect the cluster. On negative axis if number of failed attempts.",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 55 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(alertmanager_cluster_reconnections_total{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "Sucessful reconnections"
      },
      {
       "expr": "increase(alertmanager_cluster_reconnections_failed_total{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "Failed reconnections"
      }
     ]
    },
    {
     "title": "Cluster messages count on $instance",
     "type": "timeseries",
     "description": "On positive axis is number of sent cluster messages by type `update`  or `full_state` and on negative axis the same for received messages.",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 70 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(alertmanager_cluster_messages_sent_total{instance=~\"$instance\"}[$__rate_interval])) by (msg_type)",
       "legendFormat": "sent {{msg_type}}"
      },
      {
       "expr": "sum(increase(alertmanager_cluster_messages_received_total{instance=~\"$instance\"}[$__rate_interval])) by (msg_type)",
       "legendFormat": "received {{msg_type}}"
      }
     ]
    },
    {
     "title": "Cluster messages size on $instance",
     "type": "timeseries",
     "description": "On positive axis is size of sent cluster messages by type `update`  or `full_state` and on negative axis the same for received messages.",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 85 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(increase(alertmanager_cluster_messages_sent_size_total{instance=~\"$instance\"}[$__rate_interval])) by (msg_type)",
       "legendFormat": "sent {{msg_type}}"
      },
      {
       "expr": "sum(increase(alertmanager_cluster_messages_received_size_total{instance=~\"$instance\"}[$__rate_interval])) by (msg_type)",
       "legendFormat": "received {{msg_type}}"
      }
     ]
    },
    {
     "title": "Cluster messages queue on $instance",
     "type": "timeseries",
     "description": "On positive axis is number of queued cluster messages and on negative axis number of pruned messages.",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 100 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "alertmanager_cluster_messages_pruned_total{instance=~\"$instance\"}",
       "legendFormat": "Pruned messaged"
      },
      {
       "expr": "alertmanager_cluster_messages_queued{instance=~\"$instance\"}",
       "legendFormat": "Queued messages"
      }
     ]
    }
   ]
  },
  {
   "title": "Gossip messages",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Count of oversized gossip messages on $instance",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 11 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "increase(alertmanager_oversized_gossip_message_sent_total{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{key}}"
      },
      {
       "expr": "increase(alertmanager_oversized_gossip_message_dropped_total{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "dropped {{key}}"
      },
      {
       "expr": "increase(alertmanager_oversized_gossip_message_failure_total{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "failed {{key}}"
      }
     ]
    },
    {
     "title": "Duration of oversized gossip messages on $instance",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 17 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(1,rate(alertmanager_oversize_gossip_message_duration_seconds_bucket{instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "{{key}}"
      }
     ]
    },
    {
     "title": "Number of  propagated gossip messages on $instance",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 23 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(alertmanager_silences_gossip_messages_propagated_total{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "silences"
      },
      {
       "expr": "increase(alertmanager_nflog_gossip_messages_propagated_total{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "nf_log"
      }
     ]
    }
   ]
  },
  {
   "title": "Nflog",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Nf log queries count for $instance",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(alertmanager_nflog_queries_total{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "Nf log query count"
      },
      {
       "expr": "increase(alertmanager_nflog_query_errors_total{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "Nf log query errors"
      }
     ]
    },
    {
     "title": "Nf log query duration for $instance",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(1,rate(alertmanager_nflog_query_duration_seconds_bucket{instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "Nf log query duration"
      }
     ]
    },
    {
     "title": "Nf log snapshot size for $instance",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "alertmanager_nflog_snapshot_size_bytes{instance=~\"$instance\"}",
       "legendFormat": "Nf log snapshot size"
      }
     ]
    },
    {
     "title": "Nf log snapshot duration for $instance",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 30 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(alertmanager_nflog_snapshot_duration_seconds_sum{instance=~\"$instance\"}[$__rate_interval]) / rate(alertmanager_nflog_snapshot_duration_seconds_sum{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "Nf log snapshot size"
      }
     ]
    },
    {
     "title": "Nf log Go GC time for $instance",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 36 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "increase(alertmanager_nflog_gc_duration_seconds_sum{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "Cluster joined peers"
      }
     ]
    }
   ]
  }
 ]
}