{
 "title": "Besu Full",
 "description": "Provides detailed metrics of Besu nodes",
 "tags": [
  "besu",
  "ethereum"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "system",
    "label": "System",
    "query": {
     "query": "ethereum_blockchain_height{network=~\"$network\"}"
    }
   },
   {
    "name": "sync_task_quantile",
    "label": "Synchronizer Task Quantile",
    "query": {
     "query": "label_values(besu_synchronizer_task,quantile)"
    }
   },
   {
    "name": "executor",
    "label": "Executors",
    "query": {
     "query": "metrics(besu_executors_ethscheduler)"
    }
   },
   {
    "name": "vertx_pool_name",
    "label": "Vert.x Pool Name",
    "query": {
     "query": "label_values(besu_network_vertx_worker_pool_completed_total, poolName)"
    }
   },
   {
    "name": "protocol_inbound",
    "label": "Protocol Inbound",
    "query": {
     "query": "label_values(besu_network_p2p_messages_inbound_total,protocol)"
    }
   },
   {
    "name": "protocol_outbound",
    "label": "Protocol Outbound",
    "query": {
     "query": "label_values(besu_network_p2p_messages_outbound_total,protocol)"
    }
   },
   { "name": "diskdevices", "query": "[a-z]+|nvme[0-9]+n[0-9]+" },
   { "name": "overview_engine_percentiles", "query": "0.5, 0.95" },
   {
    "name": "txpool_layer",
    "label": "TxPool Layer",
    "query": {
     "query": "label_values(besu_transaction_pool_number_of_transactions, layer)"
    }
   },
   {
    "name": "network",
    "label": "Network",
    "query": {
     "query": "label_values(ethereum_blockchain_height,network)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Snap Sync",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Snap Sync Progress",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 2093 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (instance) ((besu_blockchain_height{instance=~\"$system\"} or ethereum_blockchain_height{instance=~\"$system\"}) and besu_synchronizer_snap_world_state_pending_account_requests_current{instance=~\"$system\"}  ) >0",
       "legendFormat": "Chain Height"
      },
      {
       "expr": "besu_synchronizer_fast_sync_pivot_block_current{instance=~\"$system\"} and besu_synchronizer_snap_world_state_pending_account_requests_current{instance=~\"$system\"}  >0 "
      },
      {
       "expr": "sum by (instance) (besu_synchronizer_fast_sync_pivot_block_current{instance=~\"$system\"} - (besu_blockchain_height{instance=~\"$system\"} or ethereum_blockchain_height{instance=~\"$system\"}) and besu_synchronizer_snap_world_state_pending_account_requests_current{instance=~\"$system\"}  ) >0 "
      },
      {
       "expr": "sum by (instance) (besu_synchronizer_snap_world_state_generated_nodes_total{instance=~\"$system\"} and besu_synchronizer_snap_world_state_healed_nodes_total{instance=~\"$system\"} ) >0 "
      }
     ]
    },
    {
     "title": "Nodes retrieved ",
     "type": "timeseries",
     "description": "Total number of data nodes generated and healed as part of snap sync world state download",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2102 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "besu_synchronizer_snap_world_state_generated_nodes_total{instance=~\"$system\"}",
       "legendFormat": "{{instance}}-generated-nodes"
      },
      {
       "expr": "besu_synchronizer_snap_world_state_healed_nodes_total{instance=~\"$system\"}",
       "legendFormat": "{{instance}}-healed-nodes"
      }
     ]
    },
    {
     "title": "Downloaded data",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2102 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "besu_synchronizer_snap_world_state_accounts_total{instance=~\"$system\"}",
       "legendFormat": "{{instance}}-accounts"
      },
      {
       "expr": "besu_synchronizer_snap_world_state_slots_total{instance=~\"$system\"}",
       "legendFormat": "{{instance}}-slots"
      },
      {
       "expr": "besu_synchronizer_snap_world_state_codes_total{instance=~\"$system\"}",
       "legendFormat": "{{instance}}-codes"
      }
     ]
    },
    {
     "title": "Storage pending requests",
     "type": "timeseries",
     "description": "Number of storage pending requests for snap sync world state download",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3518 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "besu_synchronizer_snap_world_state_pending_storage_requests_current{instance=~\"$system\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Account pending requests",
     "type": "timeseries",
     "description": "Number of account pending requests for snap sync world state download",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3518 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "besu_synchronizer_snap_world_state_pending_account_requests_current{instance=~\"$system\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Trie node pending requests",
     "type": "timeseries",
     "description": "Number of trie node pending requests for snap sync world state download",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3526 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "besu_synchronizer_snap_world_state_pending_trie_node_requests_current{instance=~\"$system\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Code pending requests",
     "type": "timeseries",
     "description": "Number of code pending requests for snap sync world state download",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3526 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "besu_synchronizer_snap_world_state_pending_code_requests_current{instance=~\"$system\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Blockchain pipeline entries",
     "type": "timeseries",
     "description": "Number of entries processed by each world state download pipeline stage",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3534 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "besu_synchronizer_chain_download_pipeline_processed_total{instance=~\"$system\"} != 0",
       "legendFormat": "{{instance}}-{{step}}"
      }
     ]
    },
    {
     "title": "Worldtstate pipeline entries",
     "type": "timeseries",
     "description": "Number of entries processed by each world state download pipeline stage",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3534 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "besu_synchronizer_snap_world_state_pipeline_processed_total{instance=~\"$system\"} != 0",
       "legendFormat": "{{step}}"
      }
     ]
    },
    {
     "title": "Snapsync Node Rate (10 min avg)",
     "type": "timeseries",
     "description": "Total number of data nodes healed as part of snap sync world state heal process",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3542 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(besu_synchronizer_snap_world_state_generated_nodes_total{instance=~\"$system\"}[10m]) > 0",
       "legendFormat": "{{instance}}-genetared"
      },
      {
       "expr": "rate(besu_synchronizer_snap_world_state_healed_nodes_total{instance=~\"$system\"}[10m]) > 0",
       "legendFormat": "{{instance}}-healed"
      }
     ]
    }
   ]
  },
  {
   "title": "Fast Sync",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Fast Sync Progress",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 2094 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (instance) ((besu_blockchain_height{instance=~\"$system\"} or ethereum_blockchain_height{instance=~\"$system\"}) and besu_synchronizer_world_state_pending_requests_current{instance=~\"$system\"} > 0)",
       "legendFormat": "Chain Height"
      },
      {
       "expr": "sum by (instance) (besu_synchronizer_fast_sync_pivot_block_current{instance=~\"$system\"} and besu_synchronizer_world_state_pending_requests_current{instance=~\"$system\"} > 0)"
      },
      {
       "expr": "sum by (instance) (besu_synchronizer_fast_sync_pivot_block_current{instance=~\"$system\"} - besu_blockchain_height{instance=~\"$system\"} and besu_synchronizer_world_state_pending_requests_current{instance=~\"$system\"} > 0)"
      },
      {
       "expr": "sum by (instance) (besu_synchronizer_world_state_pending_requests_current{instance=~\"$system\"} > 0)"
      },
      {
       "expr": "sum by (instance) (besu_synchronizer_world_state_completed_requests_total{instance=~\"$system\"} and besu_synchronizer_world_state_pending_requests_current{instance=~\"$system\"} > 0)"
      }
     ]
    },
    {
     "title": "Chain Height",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2103 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "ethereum_best_known_block_number{instance=~'$system'}",
       "legendFormat": "{{instance}} Best"
      },
      {
       "expr": "ethereum_blockchain_height{instance=~'$system'}",
       "legendFormat": "{{instance}} current"
      }
     ]
    },
    {
     "title": "Downloaded State Nodes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2103 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (instance) (besu_synchronizer_world_state_completed_requests_total{instance=~\"$system\"} and besu_synchronizer_world_state_pending_requests_current{instance=~\"$system\"} > 0)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Known Pending State Nodes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3519 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "besu_synchronizer_world_state_pending_requests_current{instance=~'$system'}",
       "legendFormat": "{{instance}} pending"
      },
      {
       "expr": "besu_synchronizer_world_state_existing_nodes_total{instance='$system'}",
       "legendFormat": "{{instance}} downloaded"
      }
     ]
    },
    {
     "title": "Fast Sync Node Rate (10 min avg)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3519 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(besu_synchronizer_world_state_completed_requests_total{instance=~\"$system\"}[10m])",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Overview",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance) (besu_blockchain_height{instance=~\"$system\"} or ethereum_blockchain_height{instance=~\"$system\"})",
     "legendFormat": "Chain Height"
    },
    {
     "expr": "sum by (instance) (besu_synchronizer_best_known_block{instance=~\"$system\"} or ethereum_best_known_block_number{instance=~\"$system\"})"
    },
    {
     "expr": "sum by (instance) ((besu_synchronizer_best_known_block{instance=~\"$system\"} - besu_blockchain_height{instance=~\"$system\"}) or (ethereum_best_known_block_number{instance=~\"$system\"} - ethereum_blockchain_height{instance=~\"$system\"}))"
    },
    {
     "expr": "sum by (instance) ((1/rate(besu_blockchain_height{instance=~\"$system\"}[5m])) or (1/rate(ethereum_blockchain_height{instance=~\"$system\"}[5m])))"
    },
    {
     "expr": "sum by (instance) (time() - besu_blockchain_chain_head_timestamp{instance=~\"$system\"})"
    },
    {
     "expr": "sum by (instance) (besu_peers_peer_count_current{instance=~\"$system\"} or ethereum_peer_count{instance=~\"$system\"})",
     "legendFormat": "Peer Count"
    },
    {
     "expr": "sum by (instance) ((besu_peers_peer_count_current{instance=~\"$system\"} / besu_network_peers_limit{instance=~\"$system\"}) or ethereum_peer_count{instance=~\"$system\"} / ethereum_peer_limit{instance=~\"$system\"})"
    }
   ]
  },
  {
   "title": "Block Time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "1/rate(besu_blockchain_height{instance=~\"$system\"}[5m]) or 1/rate(ethereum_blockchain_height{instance=~\"$system\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Blocks Behind",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "besu_synchronizer_best_known_block{instance=~\"$system\"} - besu_blockchain_height{instance=~\"$system\"} or ethereum_best_known_block_number{instance=~\"$system\"} - ethereum_blockchain_height{instance=~\"$system\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Connected Peers",
   "type": "timeseries",
   "description": "Describes the number of connected peers as a percentage of the maximum number of peers that can connect to the node.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(ethereum_peer_count{instance=~\"$system\"} or besu_peer_count{instance=~\"$system\"})/(ethereum_peer_limit{instance=~\"$system\"} or ethereum_peer_limit{instance=~\"$system\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Network Transactions Per Second (TPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(besu_blockchain_chain_head_transaction_count_counter_total{instance=~\"$system\"}[1h]) * besu_synchronizer_in_sync{instance=~\"$system\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Network throughput (Mgas/s)",
   "type": "timeseries",
   "description": "Describes the number of connected peers as a percentage of the maximum number of peers that can connect to the node.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(irate(besu_blockchain_chain_head_gas_used_counter_total{instance=~\"$system\"}[1h])/1000000) * besu_synchronizer_in_sync{instance=~\"$system\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Parallel vs Conflicting transactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(besu_block_processing_parallelized_transactions_counter_total{instance=~\"$system\"}[1h])",
     "legendFormat": "Parallel Tx {{instance}}"
    },
    {
     "expr": "irate(besu_block_processing_conflicted_transactions_counter_total{instance=~\"$system\"}[1h])",
     "legendFormat": "Conflicting Tx {{instance}}"
    }
   ]
  },
  {
   "title": "Execution Engine Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "newPayload time (quantile $overview_engine_percentiles)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 74 },
     "repeat": "overview_engine_percentiles",
     "targets": [
      {
       "expr": "besu_rpc_request_time{instance=~\"$system\", methodName=~\"engine_newPayloadV.*\", quantile=~\"$overview_engine_percentiles\"}",
       "legendFormat": "{{methodName}} ({{instance}})"
      }
     ]
    },
    {
     "title": "forkchoiceUpdated time (quantile $overview_engine_percentiles)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 583 },
     "repeat": "overview_engine_percentiles",
     "targets": [
      {
       "expr": "besu_rpc_request_time{instance=~\"$system\", methodName=~\"engine_forkchoiceUpdatedV.*\", quantile=~\"$overview_engine_percentiles\"}",
       "legendFormat": "{{methodName}} ({{instance}})"
      }
     ]
    }
   ]
  },
  {
   "title": "Java Memory Management",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "GC time",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "rate(jvm_gc_collection_seconds_sum{instance=~\"$system\", job=~\".*besu.*|execution.*\"}[1m])",
       "legendFormat": "{{gc}} [{{instance}}]"
      }
     ]
    },
    {
     "title": "Java Memory Used (heap+nonheap)",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "(jvm_memory_bytes_used{instance=~\"$system\", area=\"heap\", job=~\".*besu.*|execution.*\"} + ignoring(area) jvm_memory_bytes_used{instance=~\"$system\", area=\"nonheap\", job=~\".*besu.*|execution.*\"}) or (jvm_memory_used_bytes{instance=~\"$system\", area=\"heap\", job=~\".*besu.*|execution.*\"} + ignoring(area) jvm_memory_used_bytes{instance=~\"$system\", area=\"nonheap\", job=~\".*besu.*|execution.*\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Java Memory Committed (heap+nonheap)",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "(jvm_memory_bytes_committed{instance=~\"$system\", area=\"heap\", job=~\".*besu.*|execution.*\"} + ignoring(area) jvm_memory_bytes_committed{instance=~\"$system\", area=\"nonheap\", job=~\".*besu.*|execution.*\"}) or (jvm_memory_committed_bytes{instance=~\"$system\", area=\"heap\", job=~\".*besu.*|execution.*\"} + ignoring(area) jvm_memory_committed_bytes{instance=~\"$system\", area=\"nonheap\", job=~\".*besu.*|execution.*\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Flat database and Preload caches",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "Storage Preload cache",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1393 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "guava_cache_hit_total{instance=~\"$system\", cache=\"storageNodes\"}/(guava_cache_hit_total{instance=~\"$system\", cache=\"storageNodes\"}+guava_cache_miss_total{instance=~\"$system\", cache=\"storageNodes\"})",
       "legendFormat": "Hit ratio - instance {{instance}}"
      }
     ]
    },
    {
     "title": "Accounts Preload cache",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1393 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "guava_cache_hit_total{instance=~\"$system\", cache=\"accountsNodes\"}/(guava_cache_hit_total{instance=~\"$system\", cache=\"accountsNodes\"}+guava_cache_miss_total{instance=~\"$system\", cache=\"accountsNodes\"})",
       "legendFormat": "Hit ratio - instance {{instance}}"
      }
     ]
    },
    {
     "title": "Account Flat Database hit ratio",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1402 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "rate(besu_blockchain_get_account_flat_database{instance=~\"$system\"}[$__rate_interval])/rate(besu_blockchain_get_account_total{instance=~\"$system\"}[$__rate_interval]) or rate(besu_blockchain_get_account_flat_database_total{instance=~\"$system\"}[$__rate_interval])/rate(besu_blockchain_get_account_total{instance=~\"$system\"}[$__rate_interval])",
       "legendFormat": "Flat database hit ratio - accounts {{instance}}"
      },
      {
       "expr": "rate(besu_blockchain_get_account_merkle_trie{instance=~\"$system\"}[$__rate_interval])/rate(besu_blockchain_get_account_total{instance=~\"$system\"}[$__rate_interval]) or rate(besu_blockchain_get_account_merkle_trie_total{instance=~\"$system\"}[$__rate_interval])/rate(besu_blockchain_get_account_total{instance=~\"$system\"}[$__rate_interval])",
       "legendFormat": "% Merkle Patricia Trie Hits found - accounts {{instance}}"
      },
      {
       "expr": "rate(besu_blockchain_get_account_missing_merkle_trie{instance=~\"$system\"}[$__rate_interval])/rate(besu_blockchain_get_account_total{instance=~\"$system\"}[$__rate_interval]) or rate(besu_blockchain_get_account_missing_merkle_trie_total{instance=~\"$system\"}[$__rate_interval])/rate(besu_blockchain_get_account_total{instance=~\"$system\"}[$__rate_interval])",
       "legendFormat": "% Merkle Patricia Trie Hits missing - accounts {{instance}}"
      }
     ]
    },
    {
     "title": "Storage Flat Database hit ratio",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1402 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "rate(besu_blockchain_get_storagevalue_flat_database{instance=~\"$system\"}[$__rate_interval])/rate(besu_blockchain_get_storagevalue_total{instance=~\"$system\"}[$__rate_interval]) or rate(besu_blockchain_get_storagevalue_flat_database_total{instance=~\"$system\"}[$__rate_interval])/rate(besu_blockchain_get_storagevalue_total{instance=~\"$system\"}[$__rate_interval])",
       "legendFormat": "Flat database hit ratio - storage {{instance}}"
      },
      {
       "expr": "rate(besu_blockchain_get_storagevalue_merkle_trie{instance=~\"$system\"}[$__rate_interval])/rate(besu_blockchain_get_storagevalue_total{instance=~\"$system\"}[$__rate_interval]) or rate(besu_blockchain_get_storagevalue_merkle_trie_total{instance=~\"$system\"}[$__rate_interval])/rate(besu_blockchain_get_storagevalue_total{instance=~\"$system\"}[$__rate_interval])",
       "legendFormat": "% Merkle Patricia Trie Hits found - storage {{instance}}"
      },
      {
       "expr": "rate(besu_blockchain_get_storagevalue_missing_merkle_trie{instance=~\"$system\"}[$__rate_interval])/rate(besu_blockchain_get_storagevalue_total{instance=~\"$system\"}[$__rate_interval]) or rate(besu_blockchain_get_storagevalue_missing_merkle_trie_total{instance=~\"$system\"}[$__rate_interval])/rate(besu_blockchain_get_storagevalue_total{instance=~\"$system\"}[$__rate_interval])",
       "legendFormat": "% Merkle Patricia Trie Hits missing - storage {{instance}}"
      }
     ]
    },
    {
     "title": "Account Flat Database - number of calls",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1411 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(besu_blockchain_get_account_flat_database{instance=~\"$system\"}[$__rate_interval]) or rate(besu_blockchain_get_account_flat_database_total{instance=~\"$system\"}[$__rate_interval])",
       "legendFormat": "number of calls to the flat database - accounts {{instance}}"
      },
      {
       "expr": "rate(besu_blockchain_get_account_merkle_trie{instance=~\"$system\"}[$__rate_interval]) or rate(besu_blockchain_get_account_merkle_trie_total{instance=~\"$system\"}[$__rate_interval])",
       "legendFormat": "number of calls to the trie - accounts {{instance}}"
      },
      {
       "expr": "rate(besu_blockchain_get_account_missing_merkle_trie{instance=~\"$system\"}[$__rate_interval]) or rate(besu_blockchain_get_account_missing_merkle_trie_total{instance=~\"$system\"}[$__rate_interval])",
       "legendFormat": "number of calls to the trie with missing result - accounts {{instance}}"
      }
     ]
    },
    {
     "title": "Storage Flat Database - number of calls",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1411 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "irate(besu_blockchain_get_storagevalue_flat_database{instance=~\"$system\"}[$__rate_interval]) or irate(besu_blockchain_get_storagevalue_flat_database_total{instance=~\"$system\"}[$__rate_interval])",
       "legendFormat": "number of calls to the flat database - storage {{instance}}"
      },
      {
       "expr": "irate(besu_blockchain_get_storagevalue_merkle_trie{instance=~\"$system\"}[$__rate_interval]) or irate(besu_blockchain_get_storagevalue_merkle_trie_total{instance=~\"$system\"}[$__rate_interval])",
       "legendFormat": "number of calls to the trie - storage {{instance}}"
      },
      {
       "expr": "irate(besu_blockchain_get_storagevalue_missing_merkle_trie{instance=~\"$system\"}[$__rate_interval]) or irate(besu_blockchain_get_storagevalue_missing_merkle_trie_total{instance=~\"$system\"}[$__rate_interval])",
       "legendFormat": "number of calls to the trie with missing result- storage {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total disk on /data",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_filesystem_size_bytes{mountpoint=\"/data\", instance=~\"$system\"} ",
       "legendFormat": "{{instance}} "
      }
     ]
    },
    {
     "title": "Disk Usage (%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "1 - node_filesystem_avail_bytes{mountpoint=\"/data\", instance=~\"$system\"} / node_filesystem_size_bytes{mountpoint=\"/data\", instance=~\"$system\"}",
       "legendFormat": "{{instance}} Percent"
      }
     ]
    },
    {
     "title": "Disk Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_filesystem_size_bytes{mountpoint=\"/data\", instance=~\"$system\"} - node_filesystem_avail_bytes{mountpoint=\"/data\", instance=~\"$system\"}",
       "legendFormat": "{{instance}} "
      }
     ]
    },
    {
     "title": "Disk Available",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_filesystem_avail_bytes{mountpoint=\"/data\", instance=~\"$system\"}",
       "legendFormat": "{{instance}} "
      }
     ]
    },
    {
     "title": "CPU",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(process_cpu_seconds_total{instance=~\"$system\", job=~\".*besu.*|execution.*\"}[1m])",
       "legendFormat": "CPU Time IRate [{{instance}}]"
      }
     ]
    },
    {
     "title": "Physical Memory",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "process_resident_memory_bytes{instance=~'$system', job=~\".*besu.*|execution.*\"}",
       "legendFormat": "{{instance}} resident"
      }
     ]
    },
    {
     "title": "I/O Usage Read / Write",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(node_disk_read_bytes_total{instance=~\"$system\",device=~\"$diskdevices\"}[$__rate_interval])",
       "legendFormat": "{{instance}} - {{device}} - Successfully read bytes"
      },
      {
       "expr": "rate(node_disk_written_bytes_total{instance=~\"$system\",device=~\"$diskdevices\"}[$__rate_interval])",
       "legendFormat": "{{instance}} - {{device}} - Successfully written bytes"
      }
     ]
    },
    {
     "title": "Network Traffic",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "rate(node_network_receive_bytes_total{instance=~\"$system\"}[$__rate_interval])",
       "legendFormat": "{{instance}} - {{device}} - Receive"
      },
      {
       "expr": "rate(node_network_transmit_bytes_total{instance=~\"$system\", device=\"eth0\"}[$__rate_interval])*8",
       "legendFormat": "{{instance}} - {{device}} - Transmit"
      }
     ]
    },
    {
     "title": "Open File Descriptors",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "process_open_fds{instance=~\"$system\", job=~\".*besu.*|execution.*\"}",
       "legendFormat": "{{instance}} "
      }
     ]
    }
   ]
  },
  {
   "title": "Layered Transaction Pool Totals",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Transaction Count ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2111 },
     "targets": [
      {
       "expr": "sum by (instance) (besu_transaction_pool_number_of_transactions{instance=~\"$system\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Total Transaction Count By Type",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2111 },
     "targets": [
      {
       "expr": "sum by (instance, type) (besu_transaction_pool_number_of_transactions_by_type{instance=~\"$system\"})",
       "legendFormat": "{{type}} ({{instance}})"
      }
     ]
    },
    {
     "title": "Unique Senders",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2279 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by(instance) (besu_transaction_pool_unique_senders{instance=~\"$system\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Total Memory Used",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2279 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by (instance) (besu_transaction_pool_space_used{instance=~\"$system\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Remote Transaction Already Seen",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2287 },
     "targets": [
      {
       "expr": "rate(besu_transaction_pool_remote_transactions_already_seen_total{instance=~\"$system\"}[$__rate_interval])",
       "legendFormat": "{{message}} ({{instance}})"
      }
     ]
    },
    {
     "title": "Total Dropped (pool full)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2287 },
     "targets": [
      {
       "expr": "sum by(instance) (rate(besu_transaction_pool_removed_total{instance=~\"$system\", operation=\"dropped\"}[$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Total Rejected",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2295 },
     "targets": [
      {
       "expr": "rate(besu_transaction_pool_rejected_total{instance=~\"$system\", layer=~\"layertxpool|txpool\"}[$__rate_interval])",
       "legendFormat": "{{reason}} ({{instance}})"
      }
     ]
    },
    {
     "title": "Expired Messages",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2296 },
     "targets": [
      {
       "expr": "rate(besu_transaction_pool_messages_expired_total{instance=~\"$system\"}[$__rate_interval])",
       "legendFormat": "{{message}} ({{instance}})"
      }
     ]
    }
   ]
  },
  {
   "title": "Layered Transaction Pool - $txpool_layer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "repeat": "txpool_layer",
   "collapsed": true,
   "panels": [
    {
     "title": "Transaction Count ($txpool_layer)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3556 },
     "targets": [
      {
       "expr": "besu_transaction_pool_number_of_transactions{instance=~\"$system\",layer=~\"$txpool_layer\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Transaction Count By Type ($txpool_layer)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3556 },
     "targets": [
      {
       "expr": "besu_transaction_pool_number_of_transactions_by_type{instance=~\"$system\",layer=~\"$txpool_layer\"}",
       "legendFormat": "{{type}} ({{instance}})"
      }
     ]
    },
    {
     "title": "Transactions Added ($txpool_layer)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3563 },
     "targets": [
      {
       "expr": "rate(besu_transaction_pool_added_total{instance=~\"$system\",layer=~\"$txpool_layer\"}[$__rate_interval])",
       "legendFormat": "{{source}} ({{instance}})"
      }
     ]
    },
    {
     "title": "Transaction Memory Used ($txpool_layer)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3563 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "besu_transaction_pool_space_used{instance=~\"$system\",layer=~\"$txpool_layer\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Transactions Removed ($txpool_layer)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3570 },
     "targets": [
      {
       "expr": "rate(besu_transaction_pool_removed_total{instance=~\"$system\",layer=~\"$txpool_layer\"}[$__rate_interval])",
       "legendFormat": "{{source}} {{operation}} ({{instance}})"
      }
     ]
    },
    {
     "title": "Unique Senders ($txpool_layer)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3570 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "besu_transaction_pool_unique_senders{instance=~\"$system\",layer=~\"$txpool_layer\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Transactions Rejected ($txpool_layer)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3577 },
     "targets": [
      {
       "expr": "rate(besu_transaction_pool_rejected_total{instance=~\"$system\",layer=~\"$txpool_layer\"}[$__rate_interval])",
       "legendFormat": "{{source}} {{reason}} ({{instance}})"
      }
     ]
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "panels": [
    {
     "title": "Poll Size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29203 },
     "targets": [
      {
       "expr": "besu_transaction_pool_transactions{instance=~\"$system\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Added",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29203 },
     "targets": [
      {
       "expr": "rate(besu_transaction_pool_transactions_added_total{instance=~\"$system\"}[$__rate_interval])",
       "legendFormat": "{{source}} ({{instance}})"
      }
     ]
    },
    {
     "title": "Duplicates",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29211 },
     "targets": [
      {
       "expr": "rate(besu_transaction_pool_transactions_duplicates_total{instance=~\"$system\"}[$__rate_interval])",
       "legendFormat": "{{source}} ({{instance}})"
      }
     ]
    },
    {
     "title": "Removed",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29211 },
     "targets": [
      {
       "expr": "rate(besu_transaction_pool_transactions_removed_total{instance=~\"$system\"}[$__rate_interval])",
       "legendFormat": "{{source}} {{operation}} ({{instance}})"
      }
     ]
    },
    {
     "title": "Messages Skipped",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29219 },
     "targets": [
      {
       "expr": "rate(besu_transaction_pool_transactions_messages_skipped_total{instance=~\"$system\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Pending Transactions Messages Skipped",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29219 },
     "targets": [
      {
       "expr": "rate(besu_transaction_pool_pending_transactions_messages_skipped_total{instance=~\"$system\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Synchronizer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sync Duration",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9589 },
     "fieldConfig": { "defaults": { "unit": "dthms" } },
     "targets": [
      {
       "expr": "besu_synchronizer_sync_duration_sum{instance=~\"$system\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Download Pipeline",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 9597 },
     "targets": [
      {
       "expr": "rate(besu_synchronizer_chain_download_pipeline_processed_total{instance=~\"$system\"}[$__rate_interval])",
       "legendFormat": "{{step}} {{action}} ({{instance}})"
      }
     ]
    },
    {
     "title": "Pipeline Restarts",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 9597 },
     "targets": [
      {
       "expr": "rate(besu_synchronizer_chain_download_pipeline_restarts_total{instance=~\"$system\"}[$__rate_interval])",
       "legendFormat": "{{reason}} ({{instance}})"
      }
     ]
    },
    {
     "title": "AVG number of calls / second",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 9608 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(besu_synchronizer_task_count{instance=~\"$system\"}[$__rate_interval])",
       "legendFormat": "{{taskName}} ({{instance}})"
      }
     ]
    },
    {
     "title": "Task Sum",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 9608 },
     "targets": [
      {
       "expr": "rate(besu_synchronizer_task_sum{instance=~\"$system\"}[$__rate_interval])",
       "legendFormat": "{{taskName}} ({{instance}})"
      }
     ]
    },
    {
     "title": "Task time (quantile=$sync_task_quantile)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9619 },
     "repeat": "sync_task_quantile",
     "targets": [
      {
       "expr": "besu_synchronizer_task{instance=~\"$system\", quantile=~\"$sync_task_quantile\"}",
       "legendFormat": "{{taskName}} ({{instance}})"
      }
     ]
    }
   ]
  },
  {
   "title": "RPC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "AVG number of calls / second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28165 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(besu_rpc_request_time_count{instance=~\"$system\"}[$__rate_interval])",
       "legendFormat": "{{methodName}} ({{instance}})"
      }
     ]
    },
    {
     "title": "Number of errors per RPC method per type",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28165 },
     "targets": [
      {
       "expr": "rate(besu_rpc_errors_count_total{instance=~\"$system\"}[$__rate_interval])",
       "legendFormat": "{{rpcMethod}} - {{errorType}} ({{instance}})"
      }
     ]
    },
    {
     "title": "Task time (quantile=$sync_task_quantile)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28173 },
     "repeat": "sync_task_quantile",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "besu_rpc_request_time{instance=~\"$system\", quantile=~\"$sync_task_quantile\"}",
       "legendFormat": "{{methodName}} ({{instance}})"
      }
     ]
    }
   ]
  },
  {
   "title": "Peers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true,
   "panels": [
    {
     "title": "Connected by Client",
     "type": "timeseries",
     "gridPos": { "h": 18, "w": 12, "x": 0, "y": 15511 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (client) (besu_peers_peer_count_by_client{instance=~\"$system\"})",
       "legendFormat": "{{client}}"
      }
     ]
    },
    {
     "title": "Connected Peers",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15511 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "(ethereum_peer_count{instance=~\"$system\"} or besu_peer_count{instance=~\"$system\"})",
       "legendFormat": "current {{instance}}"
      },
      {
       "expr": "(ethereum_peer_limit{instance=~\"$system\"} or besu_peer_limit{instance=~\"$system\"})",
       "legendFormat": "limit {{instance}}"
      }
     ]
    },
    {
     "title": "Connected Total",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15520 },
     "targets": [
      {
       "expr": "rate(besu_peers_connected_total{instance=~\"$system\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Peers (Disconnections)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "collapsed": true,
   "panels": [
    {
     "title": "Initiator Local",
     "type": "timeseries",
     "gridPos": { "h": 17, "w": 12, "x": 0, "y": 29777 },
     "targets": [
      {
       "expr": "rate(besu_peers_disconnected_total{initiator=\"local\", instance=~\"$system\"}[$__rate_interval])",
       "legendFormat": "{{disconnectReason}} ({{instance}})"
      }
     ]
    },
    {
     "title": "Initiator Remote",
     "type": "timeseries",
     "gridPos": { "h": 17, "w": 12, "x": 12, "y": 29777 },
     "targets": [
      {
       "expr": "rate(besu_peers_disconnected_total{initiator=\"remote\", instance=~\"$system\"}[$__rate_interval])",
       "legendFormat": "{{disconnectReason}} ({{instance}})"
      }
     ]
    }
   ]
  },
  {
   "title": "Peers (Discovery)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true,
   "panels": [
    {
     "title": "Inbound Messages",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 29778 },
     "targets": [
      {
       "expr": "rate(besu_network_discovery_messages_inbound{instance=~\"$system\"}[$__rate_interval]) or rate(besu_network_discovery_messages_inbound_total{instance=~\"$system\"}[$__rate_interval])",
       "legendFormat": "{{name}} ({{instance}})"
      }
     ]
    },
    {
     "title": "Outbound Messages",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 29778 },
     "targets": [
      {
       "expr": "rate(besu_network_discovery_messages_outbound{instance=~\"$system\"}[$__rate_interval]) or rate(besu_network_discovery_messages_outbound_total{instance=~\"$system\"}[$__rate_interval])",
       "legendFormat": "{{name}} ({{instance}})"
      }
     ]
    },
    {
     "title": "Interaction Count",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 29792 },
     "targets": [
      {
       "expr": "rate(besu_network_discovery_interaction_count{instance=~\"$system\"}[$__rate_interval]) or rate(besu_network_discovery_interaction_count_total{instance=~\"$system\"}[$__rate_interval])",
       "legendFormat": "{{type}} ({{instance}})"
      }
     ]
    },
    {
     "title": "Interaction Retry Count",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 29792 },
     "targets": [
      {
       "expr": "rate(besu_network_discovery_interaction_retry_count{instance=~\"$system\"}[$__rate_interval]) or rate(besu_network_discovery_interaction_retry_count_total{instance=~\"$system\"}[$__rate_interval])",
       "legendFormat": "{{type}} ({{instance}})"
      }
     ]
    },
    {
     "title": "Inflight Interactions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29806 },
     "targets": [
      {
       "expr": "besu_network_discovery_inflight_interactions_current{instance=~\"$system\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Peers (Messages)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true,
   "panels": [
    {
     "title": "Inbound $protocol_inbound",
     "type": "timeseries",
     "gridPos": { "h": 16, "w": 24, "x": 0, "y": 20831 },
     "repeat": "protocol_inbound",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(besu_network_p2p_messages_inbound{instance=~\"$system\", protocol=\"$protocol_inbound\"}[$__rate_interval]) or increase(besu_network_p2p_messages_inbound_total{instance=~\"$system\", protocol=\"$protocol_inbound\"}[$__rate_interval])",
       "legendFormat": "{{name}} {{protocol}} ({{instance}})"
      }
     ]
    },
    {
     "title": "Outbound $protocol_outbound",
     "type": "timeseries",
     "gridPos": { "h": 16, "w": 24, "x": 0, "y": 20895 },
     "repeat": "protocol_outbound",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(besu_network_p2p_messages_outbound{instance=~\"$system\", protocol=\"$protocol_outbound\"}[$__rate_interval]) or increase(besu_network_p2p_messages_outbound_total{instance=~\"$system\", protocol=\"$protocol_outbound\"}[$__rate_interval])",
       "legendFormat": "{{name}} {{protocol}} ({{instance}})"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Threads",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "panels": [
    {
     "title": "Overview",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 29780 },
     "targets": [
      {
       "expr": "jvm_threads_current{instance=~\"$system\"}",
       "legendFormat": "current ({{instance}})"
      },
      {
       "expr": "jvm_threads_peak{instance=~\"$system\"}",
       "legendFormat": "peak ({{instance}})"
      },
      {
       "expr": "jvm_threads_daemon{instance=~\"$system\"}",
       "legendFormat": "daemon ({{instance}})"
      },
      {
       "expr": "jvm_threads_deadlocked{instance=~\"$system\"}",
       "legendFormat": "deadlocked ({{instance}})"
      },
      {
       "expr": "jvm_threads_deadlocked_monitor{instance=~\"$system\"}",
       "legendFormat": "deadlocked monitor ({{instance}})"
      }
     ]
    },
    {
     "title": "State",
     "type": "timeseries",
     "description": "Java threads",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 29780 },
     "targets": [
      {
       "expr": "jvm_threads_state{instance=~\"$system\"}",
       "legendFormat": "{{state}}({{instance}})"
      }
     ]
    },
    {
     "title": "Started",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 29792 },
     "targets": [
      {
       "expr": "jvm_threads_started_total{instance=~\"$system\"}",
       "legendFormat": "total ({{instance}})"
      }
     ]
    }
   ]
  },
  {
   "title": "Executors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "collapsed": true,
   "panels": [
    {
     "title": "$executor",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20833 },
     "repeat": "executor",
     "targets": [
      {
       "expr": "besu_executors_ethscheduler_${executor}_active_threads_current{instance=~\"$system\"}",
       "legendFormat": "active ({{instance}})"
      },
      {
       "expr": "rate(besu_executors_ethscheduler_${executor}_completed_tasks_total{instance=~\"$system\"}[$__rate_interval])",
       "legendFormat": "completed tasks/sec ({{instance}})"
      },
      {
       "expr": "besu_executors_ethscheduler_${executor}_pool_size_current{instance=~\"$system\"}",
       "legendFormat": "pool size ({{instance}})"
      },
      {
       "expr": "besu_executors_ethscheduler_${executor}_queue_length_current{instance=~\"$system\"}",
       "legendFormat": "queue length ({{instance}})"
      },
      {
       "expr": "rate(besu_executors_ethscheduler_${executor}_rejected_tasks_total{instance=~\"$system\"}[$__rate_interval])",
       "legendFormat": "rejected tasks/sec ({{instance}})"
      },
      {
       "expr": "rate(besu_executors_ethscheduler_${executor}_submitted_tasks_total{instance=~\"$system\"}[$__rate_interval])",
       "legendFormat": "submitted tasks/sec ({{instance}})"
      }
     ]
    }
   ]
  },
  {
   "title": "Vert.x",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "collapsed": true,
   "panels": [
    {
     "title": "Eventloop pending tasks",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28172 },
     "targets": [
      {
       "expr": "besu_network_vertx_eventloop_pending_tasks{instance=~\"$system\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "$vertx_pool_name",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28180 },
     "repeat": "vertx_pool_name",
     "targets": [
      {
       "expr": "rate(besu_network_vertx_worker_pool_completed_total{instance=~\"$system\", poolName=~\"$vertx_pool_name\"}[$__rate_interval])",
       "legendFormat": "completed/sec ({{instance}})"
      },
      {
       "expr": "rate(besu_network_vertx_worker_pool_rejected_total{instance=~\"$system\", poolName=~\"$vertx_pool_name\"}[$__rate_interval])",
       "legendFormat": "rejected/sec ({{instance}})"
      },
      {
       "expr": "rate(besu_network_vertx_worker_pool_submitted_total{instance=~\"$system\", poolName=~\"$vertx_pool_name\"}[$__rate_interval])",
       "legendFormat": "submitted/sec ({{instance}})"
      }
     ]
    }
   ]
  },
  {
   "title": "Netty",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pending Tasks",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29783 },
     "targets": [
      {
       "expr": "besu_network_netty_boss_pending_tasks{instance=~\"$system\"}",
       "legendFormat": "boss {{instance}}"
      },
      {
       "expr": "besu_network_netty_worker_pending_tasks{instance=~\"$system\"}",
       "legendFormat": "worker {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "RocksDB metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 29340 },
     "options": {
      "content": "# !!! WARNING !!!\n\nThe panels in this section will be empty if you didn't enable RocksDB metrics. RocksDB metrics have some overhead on Besu Performance. Please check this PR [#4038](https://github.com/hyperledger/besu/pull/4038) for more details.\n\nTo enable RocksDB metrics, you should add these config options to your besu command : \n***--metrics-protocol=PROMETHEUS --metrics-category=JVM,PROCESS,BLOCKCHAIN,ETHEREUM,EXECUTORS,NETWORK,PEERS,KVSTORE_ROCKSDB,KVSTORE_ROCKSDB_STATS,PRUNER,RPC,SYNCHRONIZER,TRANSACTION_POOL,STRATUM***\n\n"
     }
    },
    {
     "title": "Memtable Hit Ratio",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29344 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "rocksdb_memtable_hit{instance=~\"$system\"}/(rocksdb_memtable_miss{instance=~\"$system\"}+rocksdb_memtable_hit{instance=~\"$system\"})",
       "legendFormat": "rocksdb_memtable_miss- instance {{instance}}"
      }
     ]
    },
    {
     "title": "Block cache data hit ratio",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29344 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "rocksdb_block_cache_data_hit{instance=~\"$system\"}/(rocksdb_block_cache_data_hit{instance=~\"$system\"}+rocksdb_block_cache_data_miss{instance=~\"$system\"})",
       "legendFormat": "block cache data hit ratio - instance {{instance}}"
      }
     ]
    },
    {
     "title": "Block cache index hit ratio",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29353 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "rocksdb_block_cache_index_hit{instance=~\"$system\"} / (rocksdb_block_cache_index_hit{instance=~\"$system\"} + rocksdb_block_cache_index_miss{instance=~\"$system\"} )",
       "legendFormat": "Block cache index hit ratio- {{instance}}"
      }
     ]
    },
    {
     "title": "Block cache filter hit ratio",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29353 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "rocksdb_block_cache_filter_hit{instance=~\"$system\"} / (rocksdb_block_cache_filter_hit{instance=~\"$system\"} + rocksdb_block_cache_filter_miss{instance=~\"$system\"})",
       "legendFormat": "Block cache filter hit ratio - {{instance}}"
      }
     ]
    },
    {
     "title": "Besu RocksDB Get Latency 50th Percentile",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29362 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "besu_rocksdb_read_latency_seconds{instance=~\"$system\", quantile=\"0.5\"}",
       "legendFormat": "quantile=\"0.5\" - {{instance}}"
      }
     ]
    },
    {
     "title": "Besu RocksDB Get Latency 95th Percentile",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29362 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "besu_rocksdb_read_latency_seconds{instance=~\"$system\", quantile=\"0.95\"}",
       "legendFormat": " quantile=\"0.95\" - {{instance}}"
      }
     ]
    },
    {
     "title": "Besu RocksDB Get Latency 99th Percentile",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 29371 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "besu_rocksdb_read_latency_seconds{instance=~\"$system\", quantile=\"0.99\"}",
       "legendFormat": " quantile=\"0.99\" - {{instance}}"
      }
     ]
    },
    {
     "title": "RocksDB Get Latency (internal metric) 50th Percentile",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29381 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "rocksdb_db_get{instance=~\"$system\", quantile=\"0.5\"}",
       "legendFormat": "quantile=\"0.5\" - {{instance}}"
      }
     ]
    },
    {
     "title": "RocksDB Get Latency (internal metric) 95th Percentile",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29381 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "rocksdb_db_get{instance=~\"$system\", quantile=\"0.95\"}",
       "legendFormat": "quantile=\"0.95\" - {{instance}}"
      }
     ]
    },
    {
     "title": "RocksDB Get Latency (internal metric) 99th Percentile",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 29390 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "rocksdb_db_get{instance=~\"$system\", quantile=\"0.99\"}",
       "legendFormat": "quantile=\"0.99\" - {{instance}}"
      }
     ]
    },
    {
     "title": "Number of Get queries served by L0",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29401 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "irate (rocksdb_get_hit_l0{instance=~\"$system\"}[1m])",
       "legendFormat": "#Get() served by L0 - {{instance}}"
      }
     ]
    },
    {
     "title": "Number of Get queries served by L1",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29401 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "irate (rocksdb_get_hit_l1{instance=~\"$system\"}[1m])",
       "legendFormat": "#Get() served by L1 - {{instance}}"
      }
     ]
    },
    {
     "title": "Number of Get queries served by L2 and up",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29410 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "irate (rocksdb_get_hit_l2_and_up{instance=~\"$system\"}[1m])",
       "legendFormat": "#Get() served by L2 and up - {{instance}}"
      }
     ]
    },
    {
     "title": "RocksDB Block Get Latency 50th Percentile",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29410 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "rocksdb_read_block_get_micros{instance=~\"$system\", quantile=\"0.5\"}",
       "legendFormat": "quantile=\"0.5\" - {{instance}}"
      }
     ]
    },
    {
     "title": "RocksDB Block Get Latency 95th Percentile",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29419 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "rocksdb_read_block_get_micros{instance=~\"$system\", quantile=\"0.95\"}",
       "legendFormat": "quantile=\"0.95\" - {{instance}}"
      }
     ]
    },
    {
     "title": "RocksDB Block Get Latency 99th Percentile",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29419 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "rocksdb_read_block_get_micros{instance=~\"$system\", quantile=\"0.99\"}",
       "legendFormat": "quantile=\"0.99\" - {{instance}}"
      }
     ]
    },
    {
     "title": "SST Read Latency 50th Percentile",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29428 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "rocksdb_sst_read_micros{instance=~\"$system\", quantile=\"0.5\"}",
       "legendFormat": "quantile=\"0.5\" - {{instance}}"
      }
     ]
    },
    {
     "title": "SST Read Latency 95th Percentile",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29428 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "rocksdb_sst_read_micros{instance=~\"$system\", quantile=\"0.95\"}",
       "legendFormat": " quantile=\"0.95\" - {{instance}}"
      }
     ]
    },
    {
     "title": "SST Read Latency 99th Percentile",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29437 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "rocksdb_sst_read_micros{instance=~\"$system\", quantile=\"0.99\"}",
       "legendFormat": " quantile=\"0.99\" - {{instance}}"
      }
     ]
    },
    {
     "title": "Number of read keys (AVG)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29437 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "irate(rocksdb_number_keys_read{instance=~\"$system\"}[1m])",
       "legendFormat": "Number of keys read - {{instance}}"
      }
     ]
    },
    {
     "title": "RocksDB write latency 50th Percentile",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29446 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "besu_rocksdb_write_latency_seconds{database=\"blockchain\",instance=~\"$system\",quantile=\"0.5\"}",
       "legendFormat": "Quantile 0.5 - instance {{instance}}"
      }
     ]
    },
    {
     "title": "RocksDB write latency 95th Percentile",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29446 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "besu_rocksdb_write_latency_seconds{database=\"blockchain\",quantile=\"0.95\",instance=~\"$system\"}",
       "legendFormat": "Quantile 0.95 - instance {{instance}}"
      }
     ]
    },
    {
     "title": "RocksDB write latency 99th Percentile",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29455 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "besu_rocksdb_write_latency_seconds{database=\"blockchain\",instance=~\"$system\", quantile=\"0.99\"}",
       "legendFormat": "Quantile 0.99 - instance {{instance}}"
      }
     ]
    },
    {
     "title": "Number of bytes per RocksDB write 50th Percentile",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29455 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rocksdb_bytes_per_write{quantile=\"0.5\", instance=~\"$system\"}",
       "legendFormat": " quantile=\"0.5\" - {{instance}}"
      }
     ]
    },
    {
     "title": "Number of bytes per RocksDB write 95th Percentile",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29464 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rocksdb_bytes_per_write{quantile=\"0.95\", instance=~\"$system\"}",
       "legendFormat": " quantile=\"0.95\" - {{instance}}"
      }
     ]
    },
    {
     "title": "Number of bytes per RocksDB write 99th Percentile",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29464 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rocksdb_bytes_per_write{quantile=\"0.99\", instance=~\"$system\"}",
       "legendFormat": " quantile=\"0.99\" - {{instance}}"
      }
     ]
    },
    {
     "title": "Number of Blocks added to block cache",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29473 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate (rocksdb_block_cache_add{instance=~\"$system\"}[1m])",
       "legendFormat": "rocksdb_block_cache_add - {{instance}}"
      }
     ]
    },
    {
     "title": "Number of Filter blocks added to block cache",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29473 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rocksdb_block_cache_filter_add{instance=~\"$system\"}",
       "legendFormat": "rocksdb_block_cache_filter_add - {{instance}}"
      }
     ]
    },
    {
     "title": "Number of Index blocks added to block cache (Avg)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29482 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(rocksdb_block_cache_index_add{instance=~\"$system\"}[1m])",
       "legendFormat": "rocksdb_block_cache_index_add - {{instance}}"
      }
     ]
    },
    {
     "title": "Block cache bytes write (Avg)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29482 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "irate (rocksdb_block_cache_bytes_write{instance=~\"$system\"}[1m])",
       "legendFormat": "rocksdb_block_cache_bytes_write - {{instance}}"
      }
     ]
    },
    {
     "title": "Block cache bytes read (Avg)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29491 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "irate (rocksdb_block_cache_bytes_read{instance=~\"$system\"} [1m])",
       "legendFormat": "rocksdb_block_cache_bytes_read - {{instance}}"
      }
     ]
    },
    {
     "title": "Block cache filter bytes insert",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29491 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rocksdb_block_cache_filter_bytes_insert{instance=~\"$system\"}",
       "legendFormat": "rocksdb_block_cache_filter_bytes_insert - {{instance}}"
      }
     ]
    },
    {
     "title": "Block cache index bytes insert",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29500 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rocksdb_block_cache_index_bytes_insert{instance=~\"$system\"}",
       "legendFormat": "rocksdb_block_cache_index_bytes_insert - {{instance}}"
      }
     ]
    },
    {
     "title": "Number of files in a single compaction 50th Percentile",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29500 },
     "targets": [
      {
       "expr": "rocksdb_num_files_in_single_compaction{instance=~\"$system\", quantile=\"0.5\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Number of files in a single compaction 95th Percentile",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29509 },
     "targets": [
      {
       "expr": "rocksdb_num_files_in_single_compaction{instance=~\"$system\", quantile=\"0.95\"}",
       "legendFormat": " {{instance}}"
      }
     ]
    },
    {
     "title": "Number of files in a single compaction 99th Percentile",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29509 },
     "targets": [
      {
       "expr": "rocksdb_num_files_in_single_compaction{instance=~\"$system\", quantile=\"0.99\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Compaction outfile sync time 50 Percentile",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29518 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "rocksdb_compaction_outfile_sync_micros{instance=~\"$system\", quantile=\"0.5\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Compaction outfile sync time 95 Percentile",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29518 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "rocksdb_compaction_outfile_sync_micros{instance=~\"$system\", quantile=\"0.95\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Compaction outfile sync time 99 Percentile",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29527 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "rocksdb_compaction_outfile_sync_micros{instance=~\"$system\", quantile=\"0.99\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Subcompaction setup time 50 Percentile",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29527 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "rocksdb_subcompaction_setup_time{instance=~\"$system\", quantile=\"0.5\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Subcompaction setup time 95 Percentile",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29536 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "rocksdb_subcompaction_setup_time{instance=~\"$system\", quantile=\"0.95\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Subcompaction setup time 99 Percentile",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29536 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "rocksdb_subcompaction_setup_time{instance=~\"$system\", quantile=\"0.99\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Bytes Read during compaction",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29545 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "irate(rocksdb_compact_read_bytes{instance=~\"$system\"}[$__rate_interval])",
       "legendFormat": "rocksdb_compact_read_bytes - {{instance}}"
      }
     ]
    },
    {
     "title": "Bytes written during compaction",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29545 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "irate(rocksdb_compact_write_bytes{instance=~\"$system\"}[$__rate_interval])",
       "legendFormat": "rocksdb_compact_write_bytes - {{instance}}"
      }
     ]
    },
    {
     "title": "Compaction key drop cause of newer entry",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29554 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "irate(rocksdb_compaction_key_drop_newer_entry{instance=~\"$system\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Compaction key drop cause obsolete",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29554 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "irate(rocksdb_compaction_key_drop_obsolete{instance=~\"$system\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Compaction key drop cause of user",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29563 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "irate(rocksdb_compaction_key_drop_user{instance=~\"$system\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  }
 ]
}