{
 "title": "Lighthouse Sync Committee Processing",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Sync aggregate bits",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "block_sync_aggregate_set_bits" }
   ]
  },
  {
   "title": "Sync messages per second (5m avg)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "rate(beacon_sync_committee_message_processing_requests_total[5m])"
    }
   ]
  },
  {
   "title": "Sync contributions per second (1h avg)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "rate(beacon_sync_contribution_processing_requests_total[1h])"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 20 },
   "options": { "content": "# Sync committee messages" },
   "targets": [
    {}
   ]
  },
  {
   "title": "Message verification time (5m avg)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(beacon_sync_committee_message_gossip_verification_seconds_sum[5m]) / rate(beacon_sync_committee_message_gossip_verification_seconds_count[5m])"
    }
   ]
  },
  {
   "title": "Message verification time (1h avg)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(beacon_sync_committee_message_gossip_verification_seconds_sum[1h]) / rate(beacon_sync_committee_message_gossip_verification_seconds_count[1h])"
    }
   ]
  },
  {
   "title": "Message verification time (99th pc)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(beacon_sync_committee_message_gossip_verification_seconds_bucket[5m]))"
    }
   ]
  },
  {
   "title": "Message signature verification time (5m avg)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(beacon_sync_committee_message_processing_signature_seconds_sum[5m]) / rate(beacon_sync_committee_message_processing_signature_seconds_count[5m])"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 42 },
   "options": { "content": "# Sync committee contributions" },
   "targets": [
    {}
   ]
  },
  {
   "title": "Contribution verification time (5m avg)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(beacon_sync_contribution_gossip_verification_seconds_sum[5m]) / rate(beacon_sync_contribution_gossip_verification_seconds_count[5m])"
    }
   ]
  },
  {
   "title": "Contribution verification time (1h avg)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(beacon_sync_contribution_gossip_verification_seconds_sum[1h]) / rate(beacon_sync_contribution_gossip_verification_seconds_count[1h])"
    }
   ]
  },
  {
   "title": "Contribution verification time (99th pc)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(beacon_sync_contribution_gossip_verification_seconds_bucket[5m]))"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 54 },
   "options": { "content": "# Gossip statistics" },
   "targets": [
    {}
   ]
  },
  {
   "title": "Invalid gossip messages by type",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "sum(increase(gossipsub_sync_committee_errors_per_type{type != \"SyncContributionAlreadyKnown\", type != \"PastSlot\"}[5m])) by (type)"
    }
   ]
  },
  {
   "title": "Duplicate sync contributions per second (1h avg)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 56 },
   "targets": [
    {
     "expr": "rate(gossipsub_sync_committee_errors_per_type{type = \"SyncContributionAlreadyKnown\"}[1h])"
    }
   ]
  },
  {
   "title": "Late sync contributions per second (5m avg)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 56 },
   "targets": [
    {
     "expr": "rate(gossipsub_sync_committee_errors_per_type{type = \"PastSlot\"}[5m])"
    }
   ]
  }
 ]
}