{
 "title": "Teku - Detailed",
 "description": "Dashboard to monitor multiple Teku instances.",
 "tags": [
  "teku",
  "ethereum",
  "eth2.0"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "system",
    "label": "System",
    "query": {
     "query": "validator_local_validator_count{network=~\"$network\",alerting=~\"$alerting\"}"
    }
   },
   { "name": "network", "label": "Network", "query": { "query": "label_values(network)" } },
   { "name": "alerting", "label": "Alerting", "query": { "query": "label_values(alerting)" } }
  ]
 },
 "panels": [
  { "title": "Validator", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Local Validators",
   "type": "stat",
   "description": "Number of local validators",
   "gridPos": { "h": 4, "w": 20, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum by (status) (validator_local_validator_counts{instance=~\"$system\"}))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Teku Versions",
   "type": "table",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "targets": [
    {
     "expr": "sum by (version) (beacon_teku_version{instance=~\"$system\"}) or sum by (version) (beacon_teku_version_total{instance=~\"$system\"})",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Published Blocks",
   "type": "stat",
   "description": "Number of blocks published",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(validator_beacon_node_requests_total{instance=~\"$system\",method=\"publish_block\",outcome=\"success\"})"
    }
   ]
  },
  {
   "title": "Published Attestations",
   "type": "stat",
   "description": "Number of attestations published",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(validator_beacon_node_requests_total{instance=~\"$system\",method=\"publish_attestation\",outcome=\"success\"})"
    }
   ]
  },
  {
   "title": "Published Aggregates",
   "type": "stat",
   "description": "Number of aggregates published",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(validator_beacon_node_requests_total{instance=~\"$system\",method=\"publish_aggregate_and_proofs\",outcome=\"success\"})"
    }
   ]
  },
  {
   "title": "Published Sync Committee Messages",
   "type": "stat",
   "description": "Number of sync committee messages published.",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(validator_beacon_node_requests_total{instance=~\"$system\",method=\"send_sync_committee_messages\",outcome=\"success\"})"
    }
   ]
  },
  {
   "title": "Total Validators",
   "type": "stat",
   "description": "Total number of active validators in the network.",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(beacon_current_active_validators{instance=~\"$system\"})"
    }
   ]
  },
  {
   "title": "Attestation Performance",
   "type": "timeseries",
   "description": "Percentage of attestations in each epoch with the correct head root, correct target root and that were successfully included in blocks.",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "clamp_max(avg((validator_performance_included_attestations{instance=~\"$system\"} / validator_performance_expected_attestations{instance=~\"$system\"}) >= 0), 1)",
     "legendFormat": "{{instance}} Included"
    },
    {
     "expr": "clamp_max(avg((validator_performance_correct_head_block_count{instance=~\"$system\"} / validator_performance_included_attestations{instance=~\"$system\"}) >= 0), 1)",
     "legendFormat": "{{instance}} Correct Head"
    },
    {
     "expr": "avg((validator_performance_correct_target_count{instance=~\"$system\"} / validator_performance_included_attestations{instance=~\"$system\"}) >= 0)",
     "legendFormat": "{{instance}} Correct Target"
    },
    {
     "expr": "clamp_max(avg(\n((\nvalidator_performance_correct_head_block_count{instance=~\"$system\"} - (validator_performance_expected_attestations{instance=~\"$system\"} - validator_performance_correct_head_block_count{instance=~\"$system\"}) +\nvalidator_performance_correct_target_count{instance=~\"$system\"} - (validator_performance_expected_attestations{instance=~\"$system\"} - validator_performance_correct_target_count{instance=~\"$system\"}) +\nvalidator_performance_included_attestations{instance=~\"$system\"} - (validator_performance_expected_attestations{instance=~\"$system\"} - validator_performance_included_attestations{instance=~\"$system\"}) +\n(0.875  * validator_performance_included_attestations{instance=~\"$system\"} / validator_performance_inclusion_distance_average{instance=~\"$system\"})\n) / validator_performance_expected_attestations{instance=~\"$system\"} / 3.875)>=0), 1)",
     "legendFormat": "{{instance}} Attestation Rewards Earned"
    },
    {
     "expr": "clamp_max(avg((validator_performance_included_sync_committee_messages{instance=~\"$system\"} / validator_performance_expected_sync_committee_messages{instance=~\"$system\"}) >= 0), 1)",
     "legendFormat": "{{instance}} Included Signatures"
    },
    {
     "expr": "clamp_max(avg((validator_performance_produced_sync_committee_messages{instance=~\"$system\"} / validator_performance_expected_sync_committee_messages{instance=~\"$system\"}) >= 0), 1)",
     "legendFormat": "{{instance}} Produced Signatures"
    },
    {
     "expr": "clamp_max(avg((validator_performance_correct_sync_committee_messages{instance=~\"$system\"} / validator_performance_produced_sync_committee_messages{instance=~\"$system\"}) >= 0), 1)",
     "legendFormat": "{{instance}} Correct Signatures"
    },
    {
     "expr": "clamp_max(avg((validator_performance_produced_attestations{instance=~\"$system\"} / validator_performance_expected_attestations{instance=~\"$system\"}) >= 0), 1)",
     "legendFormat": "{{instance}} Produced"
    }
   ]
  },
  {
   "title": "Attestation Inclusion Distance (slots)",
   "type": "timeseries",
   "description": "Number of slots between when an attestation is created to when it is included in a block. The minimum possible inclusion distance is 1.",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "validator_performance_inclusion_distance_min{instance=~\"$system\"}",
     "legendFormat": "{{instance}} Minimum"
    },
    {
     "expr": "validator_performance_inclusion_distance_average{instance=~\"$system\"}",
     "legendFormat": "{{instance}} Average"
    },
    {
     "expr": "validator_performance_inclusion_distance_max{instance=~\"$system\"}",
     "legendFormat": "{{instance}} Maximum"
    }
   ]
  },
  {
   "title": "Included Blocks",
   "type": "timeseries",
   "description": "Percentage of blocks produced in each epoch that were successfully included in the canonical chain.",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "validator_performance_included_blocks{instance=~\"$system\"} / validator_performance_expected_blocks{instance=~\"$system\"}",
     "legendFormat": "{{instance}} Included Blocks"
    }
   ]
  },
  {
   "title": "Attestation Inclusion Detail",
   "type": "timeseries",
   "description": "Percentage of attestations in each epoch with the correct head root, correct target root and that were successfully included in blocks.",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "clamp_max((validator_performance_included_attestations{instance=~\"$system\"} / validator_performance_expected_attestations{instance=~\"$system\"} >= 0), 1)",
     "legendFormat": "{{instance}} Included"
    }
   ]
  },
  {
   "title": "Correct Head Detail",
   "type": "timeseries",
   "description": "Percentage of attestations in each epoch with the correct head root, correct target root and that were successfully included in blocks.",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "clamp_max((validator_performance_correct_head_block_count{instance=~\"$system\"} / validator_performance_included_attestations{instance=~\"$system\"} >= 0), 1)",
     "legendFormat": "{{instance}} Correct Head"
    }
   ]
  },
  {
   "title": "Validator Timings",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Attestation Production Delay",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 88 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (interval) (rate(validator_attestation_publication_delay{instance=~\"$system\"}[5m])) or sum by (interval) (rate(validator_attestation_publication_delay_total{instance=~\"$system\"}[5m]))",
       "legendFormat": "{{interval}}"
      }
     ]
    },
    {
     "title": "Block Production Delay",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 88 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (interval) (rate(validator_block_publication_delay{instance=~\"$system\"}[$__range])) or sum by (interval) (rate(validator_block_publication_delay_total{instance=~\"$system\"}[$__range]))",
       "legendFormat": "{{interval}}"
      }
     ]
    },
    {
     "title": "Attestation Delays",
     "type": "piechart",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 160 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (interval) (increase(validator_attestation_publication_delay{instance=~\"$system\"}[$__range])) or sum by (interval) (increase(validator_attestation_publication_delay_total{instance=~\"$system\"}[$__range]))",
       "legendFormat": "{{interval}}"
      }
     ]
    },
    {
     "title": "Block Delays",
     "type": "piechart",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 160 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (interval) (increase(validator_block_publication_delay{instance=~\"$system\"}[$__range])) or sum by (interval) (increase(validator_block_publication_delay_total{instance=~\"$system\"}[$__range]))",
       "legendFormat": "{{interval}}"
      }
     ]
    }
   ]
  },
  { "title": "Beacon Chain", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Current slot",
   "type": "stat",
   "description": "Current slot according to system time",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max by (network) (beacon_slot{instance=~\"$system\"})",
     "legendFormat": "{{network}}"
    }
   ]
  },
  {
   "title": "Head slot",
   "type": "stat",
   "description": "Slot of the latest imported block",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (network) (beacon_head_slot{instance=~\"$system\"})",
     "legendFormat": "{{network}}"
    }
   ]
  },
  {
   "title": "Justified Epoch",
   "type": "stat",
   "description": "Current justified epoch",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (network) (beacon_current_justified_epoch{instance=~\"$system\"})",
     "legendFormat": "{{network}}"
    }
   ]
  },
  {
   "title": "Finalized Epoch",
   "type": "stat",
   "description": "Current finalized epoch",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (network) (beacon_finalized_epoch{instance=~\"$system\"})",
     "legendFormat": "{{network}}"
    }
   ]
  },
  {
   "title": "Peer Count",
   "type": "stat",
   "description": "Total number of peers connected to the selected nodes.",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (network) (beacon_peer_count{instance=~\"$system\"})",
     "legendFormat": "{{network}}"
    }
   ]
  },
  {
   "title": "Current Epoch",
   "type": "stat",
   "description": "The current epoch according to system time",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (network) (beacon_epoch{instance=~\"$system\"})",
     "legendFormat": "{{network}}"
    }
   ]
  },
  {
   "title": "Slots Behind",
   "type": "stat",
   "description": "Number of slots the head block is behind.",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "uniqueValues" ] } },
   "targets": [
    {
     "expr": "max without (alerting, job, instance, client) (beacon_slot{instance=~\"$system\"} - beacon_head_slot{instance=~\"$system\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Justification Delay (epochs)",
   "type": "stat",
   "description": "Number of epochs that justification has been delayed.",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_min(min without (instance, job, alerting, client) (beacon_epoch{instance=~\"$system\"} - beacon_current_justified_epoch{instance=~\"$system\"} - 1), 0)",
     "legendFormat": "{{network}}"
    }
   ]
  },
  {
   "title": "Finalisation Delay (epochs)",
   "type": "stat",
   "description": "Number of epochs that finalisation has been delayed.",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_min(min without (instance, job, alerting, client) (beacon_epoch{instance=~\"$system\"} - beacon_finalized_epoch{instance=~\"$system\"} - 2), 0)",
     "legendFormat": "{{network}}"
    }
   ]
  },
  {
   "title": "Network Participation Rate",
   "type": "stat",
   "description": "Percentage of validators which voted for the correct target in the previous epoch.",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (network) (beacon_previous_correct_validators{instance=~\"$system\"} / beacon_previous_active_validators{instance=~\"$system\"})",
     "legendFormat": "{{network}}"
    }
   ]
  },
  {
   "title": "Trailing Distance",
   "type": "timeseries",
   "description": "Number of slots the head block is behind the current slot. Empty slots may mean the head block trails by a few slots.",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "clamp_min(beacon_slot{instance=~\"$system\"} - beacon_head_slot{instance=~\"$system\"}, 0)",
     "legendFormat": "{{instance}} Head Slot"
    },
    {
     "expr": "clamp_min(min(beacon_epoch{instance=~\"$system\"} - beacon_current_justified_epoch{instance=~\"$system\"} - 1) without (instance), 0)",
     "legendFormat": "Justification Delay"
    },
    {
     "expr": "clamp_min(min(beacon_epoch{instance=~\"$system\"} - beacon_finalized_epoch{instance=~\"$system\"} - 2) without (instance), 0)",
     "legendFormat": "Finalisation Delay"
    }
   ]
  },
  {
   "title": "Participation Rate",
   "type": "timeseries",
   "description": "Overall participation rate in the chain. The Correct Validators must be above 2/3rd for the chain to finalize.",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max by (network) (beacon_previous_live_validators{instance=~\"$system\"} / beacon_previous_active_validators{instance=~\"$system\"})",
     "legendFormat": "{{network}} Live Validators"
    },
    {
     "expr": "max by (network) (beacon_previous_correct_validators{instance=~\"$system\"} / beacon_previous_active_validators{instance=~\"$system\"})",
     "legendFormat": "{{network}} Correct Validators"
    },
    {
     "expr": "max by (network) (beacon_previous_live_sync_committee{instance=~\"$system\"} / (512 * 32))",
     "legendFormat": "{{network}} Sync Committee Participation"
    }
   ]
  },
  {
   "title": "Peer Client Software",
   "type": "timeseries",
   "description": "Breakdown of client software run by peers. Note that software cannot always be determined for peers and percentage of peers isn't indicative of number of validators using that software.",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 36 },
   "targets": [
    {
     "expr": "sum by (exported_client, client) (libp2p_connected_peers_current{instance=~\"$system\"})",
     "legendFormat": "{{exported_client}}"
    }
   ]
  },
  {
   "title": "Beacon Node Block Production",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "Prepared Proposers",
     "type": "stat",
     "description": "Total number of prepared proposers",
     "gridPos": { "h": 3, "w": 12, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(beacon_proposers_data_total{instance=~\"$system\", type=\"prepared_proposers\"}) or sum(beacon_proposers_data{instance=~\"$system\", type=\"prepared_proposers\"})"
      }
     ]
    },
    {
     "title": "Registered Validators",
     "type": "stat",
     "description": "Total number of registered validators willing to produce blocks using builder infrastructure",
     "gridPos": { "h": 3, "w": 12, "x": 12, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(beacon_proposers_data_total{instance=~\"$system\", type=\"registered_validators\"}) or sum(beacon_proposers_data{instance=~\"$system\", type=\"registered_validators\"})"
      }
     ]
    },
    {
     "title": "Execution Payload Source",
     "type": "piechart",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 71 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (source) (increase(beacon_execution_payload_source{instance=~\"$system\"}[$__range])) or sum by (source) (increase(beacon_execution_payload_source_total{instance=~\"$system\"}[$__range]))",
       "legendFormat": "{{source}}"
      }
     ]
    },
    {
     "title": "Execution Payload Fallback Reason",
     "type": "piechart",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 71 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (fallback_reason) (increase(beacon_execution_payload_source{instance=~\"$system\", source=\"builder_local_el_fallback\", fallback_reason!~\"\"}[$__range])) or sum by (fallback_reason) (increase(beacon_execution_payload_source_total{instance=~\"$system\", source=\"builder_local_el_fallback\", fallback_reason!~\"\"}[$__range]))",
       "legendFormat": "{{fallback_reason}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Beacon Node Builder API Client",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 12, "x": 0, "y": 48 },
     "options": {
      "content": "<h2 style=\"color: #eb7b18; font-size: 17px;\">\n<center>Builder Status API</center>\n</h2>"
     }
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 12, "x": 12, "y": 48 },
     "options": {
      "content": "<h2 style=\"color: #eb7b18; font-size: 17px;\">\n<center>Builder Validator Registration API</center>\n</h2>"
     }
    },
    {
     "type": "timeseries",
     "description": "Builder Status API",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 71 },
     "targets": [
      {
       "expr": "sum by (interval) (rate(beacon_builder_requests_total{instance=~\"$system\", method=\"status\"}[5m]))",
       "legendFormat": "{{interval}}"
      },
      {
       "expr": "sum by (outcome) (rate(beacon_builder_requests_total{instance=~\"$system\", method=\"status\", outcome=\"error\"}[5m]))",
       "legendFormat": "FAILED"
      }
     ]
    },
    {
     "type": "timeseries",
     "description": "Builder Validator Registration API",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 71 },
     "targets": [
      {
       "expr": "sum by (interval) (rate(beacon_builder_requests_total{instance=~\"$system\", method=\"register_validators\"}[5m]))",
       "legendFormat": "{{interval}}"
      },
      {
       "expr": "sum by (outcome) (rate(beacon_builder_requests_total{instance=~\"$system\", method=\"register_validators\", outcome=\"error\"}[5m]))",
       "legendFormat": "FAILED"
      }
     ]
    },
    {
     "type": "piechart",
     "description": "Builder Validator Registration API",
     "gridPos": { "h": 9, "w": 3, "x": 0, "y": 82 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (outcome) (increase(beacon_builder_requests_total{instance=~\"$system\", method=\"status\"}[$__range]))",
       "legendFormat": "{{outcome}}"
      }
     ]
    },
    {
     "type": "piechart",
     "description": "Builder Status API",
     "gridPos": { "h": 9, "w": 9, "x": 3, "y": 82 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (interval) (increase(beacon_builder_requests_total{instance=~\"$system\", method=\"status\"}[$__range]))",
       "legendFormat": "{{interval}}"
      }
     ]
    },
    {
     "type": "piechart",
     "description": "Builder Validator Registration API",
     "gridPos": { "h": 9, "w": 3, "x": 12, "y": 82 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (outcome) (increase(beacon_builder_requests_total{instance=~\"$system\", method=\"register_validators\"}[$__range]))",
       "legendFormat": "{{outcome}}"
      }
     ]
    },
    {
     "type": "piechart",
     "description": "Builder Validator Registration API",
     "gridPos": { "h": 9, "w": 9, "x": 15, "y": 82 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (interval) (increase(beacon_builder_requests_total{instance=~\"$system\", method=\"register_validators\"}[$__range]))",
       "legendFormat": "{{interval}}"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 12, "x": 0, "y": 91 },
     "options": {
      "content": "<h2 style=\"color: #eb7b18; font-size: 17px;\">\n<center>Builder Get Header API</center>\n</h2>"
     }
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 12, "x": 12, "y": 91 },
     "options": {
      "content": "<h2 style=\"color: #eb7b18; font-size: 17px;\">\n<center>Builder Get Payload API</center>\n</h2>"
     }
    },
    {
     "type": "timeseries",
     "description": "Builder Get Header API",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 93 },
     "targets": [
      {
       "expr": "sum by (interval) (rate(beacon_builder_requests_total{instance=~\"$system\", method=\"get_header\"}[5m]))",
       "legendFormat": "{{interval}}"
      },
      {
       "expr": "sum by (outcome) (rate(beacon_builder_requests_total{instance=~\"$system\", method=\"get_header\", outcome=\"error\"}[5m]))",
       "legendFormat": "FAILED"
      }
     ]
    },
    {
     "type": "timeseries",
     "description": "Builder Get Payload API",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 93 },
     "targets": [
      {
       "expr": "sum by (interval) (rate(beacon_builder_requests_total{instance=~\"$system\", method=\"get_payload\"}[5m]))",
       "legendFormat": "{{interval}}"
      },
      {
       "expr": "sum by (outcome) (rate(beacon_builder_requests_total{instance=~\"$system\", method=\"get_payload\", outcome=\"error\"}[5m]))",
       "legendFormat": "FAILED"
      }
     ]
    },
    {
     "type": "piechart",
     "description": "Builder Get Header API",
     "gridPos": { "h": 9, "w": 3, "x": 0, "y": 104 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (outcome) (increase(beacon_builder_requests_total{instance=~\"$system\", method=\"get_header\"}[$__range]))",
       "legendFormat": "{{outcome}}"
      }
     ]
    },
    {
     "type": "piechart",
     "description": "Builder Get Header API",
     "gridPos": { "h": 9, "w": 9, "x": 3, "y": 104 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (interval) (increase(beacon_builder_requests_total{instance=~\"$system\", method=\"get_header\"}[$__range]))",
       "legendFormat": "{{interval}}"
      }
     ]
    },
    {
     "type": "piechart",
     "description": "Builder Get Payload API",
     "gridPos": { "h": 9, "w": 3, "x": 12, "y": 104 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (outcome) (increase(beacon_builder_requests_total{instance=~\"$system\", method=\"get_payload\"}[$__range]))",
       "legendFormat": "{{outcome}}"
      }
     ]
    },
    {
     "type": "piechart",
     "description": "Builder Get Payload API",
     "gridPos": { "h": 9, "w": 9, "x": 15, "y": 104 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (interval) (increase(beacon_builder_requests_total{instance=~\"$system\", method=\"get_payload\"}[$__range]))",
       "legendFormat": "{{interval}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Block Timings",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "collapsed": true,
   "panels": [
    {
     "title": "Block Arrival Delays",
     "type": "piechart",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 49 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (interval) (increase(beacon_block_import_delay_counter{instance=~\"$system\", stage=\"arrival\"}[$__range])) or sum by (interval) (increase(beacon_block_import_delay_counter_total{instance=~\"$system\", stage=\"arrival\"}[$__range]))",
       "legendFormat": "{{interval}}"
      }
     ]
    },
    {
     "title": "Block Total Processing Time",
     "type": "piechart",
     "description": "Block total processing time for successfully imported blocks",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 49 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (interval) (increase(beacon_block_import_delay_counter{instance=~\"$system\", stage=\"total_processing_time\", result=\"success\"}[$__range])) or sum by (interval) (increase(beacon_block_import_delay_counter_total{instance=~\"$system\", stage=\"total_processing_time\", result=\"success\"}[$__range]))",
       "legendFormat": "{{interval}}"
      }
     ]
    },
    {
     "title": "Wait for Block Execution Layer Processing Time",
     "type": "piechart",
     "description": "How long Teku waited for the execution layer to finish block processing",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 81 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (interval) (increase(beacon_block_import_delay_counter{instance=~\"$system\", stage=\"execution_payload_result_received\"}[$__range])) or sum by (interval) (increase(beacon_block_import_delay_counter_total{instance=~\"$system\", stage=\"execution_payload_result_received\"}[$__range]))",
       "legendFormat": "{{interval}}"
      }
     ]
    },
    {
     "title": "Failed block import",
     "type": "piechart",
     "description": "Block import failures grouped by failure reason",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 81 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (result) (increase(beacon_block_import_delay_counter{instance=~\"$system\", stage=\"total_processing_time\", result!=\"success\"}[$__range])) or sum by (result) (increase(beacon_block_import_delay_counter_total{instance=~\"$system\", stage=\"total_processing_time\", result!=\"success\"}[$__range]))",
       "legendFormat": "{{interval}}"
      }
     ]
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{instance=~\"$system\"}[1m])",
     "legendFormat": "{{instance}} {{job}}"
    },
    {
     "expr": "sum by (instance) (irate(node_cpu_seconds_total{instance=~\"$system\",mode!=\"idle\"}[1m]))",
     "legendFormat": "{{instance}} Total"
    }
   ]
  },
  {
   "title": "Old Gen Heap Usage",
   "type": "timeseries",
   "description": "Percentage of old gen heap used.",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(jvm_memory_pool_bytes_used{job=\"besu-node\", pool=\"G1 Old Gen\", instance=~\"$system\"} / jvm_memory_pool_bytes_max{job=\"besu-node\", pool=\"G1 Old Gen\", instance=~\"$system\"}) * 100  or (jvm_memory_pool_used_bytes{job=\"besu-node\", pool=\"G1 Old Gen\", instance=~\"$system\"} / jvm_memory_pool_max_bytes{job=\"besu-node\", pool=\"G1 Old Gen\", instance=~\"$system\"}) * 100  ",
     "legendFormat": "{{instance}} {{job}}"
    },
    {
     "expr": "(jvm_memory_pool_bytes_used{job=\"teku-node\", pool=\"G1 Old Gen\", instance=~\"$system\"} / jvm_memory_pool_bytes_max{job=\"teku-node\", pool=\"G1 Old Gen\", instance=~\"$system\"}) * 100 or (jvm_memory_pool_used_bytes{job=\"teku-node\", pool=\"G1 Old Gen\", instance=~\"$system\"} / jvm_memory_pool_max_bytes{job=\"teku-node\", pool=\"G1 Old Gen\", instance=~\"$system\"}) * 100",
     "legendFormat": "{{instance}} {{job}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_used{instance=~\"$system\"} or jvm_memory_pool_used_bytes{instance=~\"$system\"}",
     "legendFormat": "{{instance}} {{job}} {{pool}} Used"
    },
    {
     "expr": "sum by (instance) (jvm_memory_pool_bytes_used{instance=~\"$system\"}) or sum by (instance) (jvm_memory_pool_used_bytes{instance=~\"$system\"})",
     "legendFormat": "{{instance}} {{job}} {{pool}} Used Total"
    },
    {
     "expr": "process_resident_memory_bytes{instance=~\"$system\"}",
     "legendFormat": "{{instance}} {{job}} {{pool}} Process Total"
    },
    {
     "expr": " (jvm_memory_pool_bytes_max{instance=~\"$system\"}) or (jvm_memory_pool_max_bytes{instance=~\"$system\"})",
     "legendFormat": "{{instance}} {{job}} {{pool}} Max"
    }
   ]
  },
  {
   "title": "GC Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{instance=~\"$system\"}[1m])",
     "legendFormat": "{{instance}} {{job}} {{gc}}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Traffic",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by (instance) (irate(node_network_transmit_bytes_total{instance=~\"$system\"}[1m]))",
       "legendFormat": "{{instance}} Transmit"
      },
      {
       "expr": "sum by (instance) (irate(node_network_receive_bytes_total{instance=~\"$system\"}[1m]))",
       "legendFormat": "{{instance}} Receive"
      }
     ]
    },
    {
     "title": "Gossip Messages",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (instance)(irate(libp2p_gossip_messages_total{instance=~\"$system\"}[1m]))",
       "legendFormat": "{{instance}} Total"
      },
      {
       "expr": "irate(libp2p_gossip_messages_total{instance=~\"$system\"}[1m])",
       "legendFormat": "{{instance}} {{topic}}"
      }
     ]
    },
    {
     "title": "RPC Blocks and Blob sidecars Requested",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "irate(etwork_rpc_blocks_by_root_requested_blocks_total{instance=~\"$system\"}[1m])",
       "legendFormat": "{{instance}} Blocks By Root"
      },
      {
       "expr": "irate(network_rpc_blocks_by_range_requested_blocks_total{instance=~\"$system\"}[1m])",
       "legendFormat": "{{instance}} Blocks By Range"
      },
      {
       "expr": "irate(network_rpc_blob_sidecars_by_range_requested_sidecars_total{instance=~\"$system\"}[1m])",
       "legendFormat": "{{instance}} Blob sidecars By Range"
      },
      {
       "expr": "irate(network_rpc_blob_sidecars_by_root_requested_blob_sidecars_total{instance=~\"$system\"}[1m])",
       "legendFormat": "{{instance}} Blob sidecars By Root"
      }
     ]
    },
    {
     "title": "Peer Disconnect Reasons",
     "type": "piechart",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (reason) (increase(network_peer_goodbye_total{instance=~\"$system\"}[$__range]))",
       "legendFormat": "{{reason}}"
      }
     ]
    },
    {
     "title": "Peer Chain Validation Attempts",
     "type": "piechart",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (status) (increase(network_peer_chain_validation_attempts{instance=~\"$system\",status!=\"started\"}[$__range])) or sum by (status) (increase(network_peer_chain_validation_attempts_total{instance=~\"$system\",status!=\"started\"}[$__range]))",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "Peer Count By Subnet",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "network_subnet_peer_count{instance=~\"$system\", subnet=~\"attestation.*\"}",
       "legendFormat": "{{instance}} {{subnet}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Space Used",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "1 - node_filesystem_avail_bytes{instance=~\"$system\",mountpoint=~\"(/data|/)\"} / node_filesystem_size_bytes{instance=~\"$system\"}",
       "legendFormat": "{{instance}} {{mountpoint}}"
      }
     ]
    },
    {
     "title": "Disk Active Time",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "irate(node_disk_io_time_seconds_total{instance=~\"$system\"}[1m])",
       "legendFormat": "{{instance}} {{device}} IO Time"
      }
     ]
    },
    {
     "title": "Disk Latency",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "irate(node_disk_read_time_seconds_total{instance=~\"$system\"}[1m]) / irate(node_disk_reads_completed_total{instance=~\"$system\"}[1m])",
       "legendFormat": "{{instance}} {{device}} Read Latency"
      },
      {
       "expr": "irate(node_disk_write_time_seconds_total{instance=~\"$system\"}[1m]) / irate(node_disk_writes_completed_total{instance=~\"$system\"}[1m])",
       "legendFormat": "{{instance}} {{device}} Write Latency"
      }
     ]
    }
   ]
  },
  {
   "title": "Queues, Excecutors and Caches",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 },
   "collapsed": true,
   "panels": [
    {
     "title": "Batch Signature Verification Queue Size",
     "type": "timeseries",
     "description": "Tracks number of signatures waiting to be batch verified",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "executor_signature_verifications_queue_size{instance=~\"$system\"}",
       "legendFormat": "{{instance}}"
      },
      {
       "expr": "avg without (instance) (executor_signature_verifications_queue_size{instance=~\"$system\"})",
       "legendFormat": "Average"
      },
      {
       "expr": "max without (instance) (executor_signature_verifications_queue_size{instance=~\"$system\"})",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "Signature Verification Batch Size",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "irate(executor_signature_verifications_task_count{instance=~\"$system\"}[1m]) / irate(executor_signature_verifications_batch_count{instance=~\"$system\"}[1m]) or irate(executor_signature_verifications_task_count_total{instance=~\"$system\"}[1m]) / irate(executor_signature_verifications_batch_count_total{instance=~\"$system\"}[1m])",
       "legendFormat": "{{instance}}"
      },
      {
       "expr": "avg without (instance) (irate(executor_signature_verifications_task_count{instance=~\"$system\"}[1m]) / irate(executor_signature_verifications_batch_count{instance=~\"$system\"}[1m])) or avg without (instance) (irate(executor_signature_verifications_task_count_total{instance=~\"$system\"}[1m]) / irate(executor_signature_verifications_batch_count_total{instance=~\"$system\"}[1m]))",
       "legendFormat": "Average"
      },
      {
       "expr": "max without (instance) (irate(executor_signature_verifications_task_count{instance=~\"$system\"}[1m]) / irate(executor_signature_verifications_batch_count{instance=~\"$system\"}[1m])) or max without (instance) (irate(executor_signature_verifications_task_count_total{instance=~\"$system\"}[1m]) / irate(executor_signature_verifications_batch_count_total{instance=~\"$system\"}[1m]))",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "Signature Verification Batch Size",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "executor_signature_verifications_batch_size{instance=~\"$system\"}",
       "legendFormat": "{{instance}} {{quantile}}"
      },
      {
       "expr": "avg without (instance) (executor_signature_verifications_batch_size{instance=~\"$system\"})",
       "legendFormat": "Average {{quantile}}"
      }
     ]
    },
    {
     "title": "Pending Pool Size",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "beacon_pending_pool_size{instance=~\"$system\"}",
       "legendFormat": "{{instance}} Pending {{type}}"
      },
      {
       "expr": "beacon_future_items_size{instance=~\"$system\"}",
       "legendFormat": "{{instance}} Future {{type}}"
      }
     ]
    },
    {
     "title": "Executor Queues",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "executor_queue_size{instance=~\"$system\"}",
       "legendFormat": "{{instance}} {{name}}"
      }
     ]
    },
    {
     "title": "In Memory Storage",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "storage_memory_states_cache_size{instance=~\"$system\"}",
       "legendFormat": "{{instance}} States"
      },
      {
       "expr": "storage_memory_block_count{instance=~\"$system\"}",
       "legendFormat": "{{instance}} Blocks"
      },
      {
       "expr": "storage_memory_checkpoint_states_cache_size{instance=~\"$system\"}",
       "legendFormat": "{{instance}} Checkpoint States"
      },
      {
       "expr": "storage_memory_epoch_states_cache_size{instance=~\"$system\"}",
       "legendFormat": "{{instance}} Epoch States"
      }
     ]
    },
    {
     "title": "Event Channels",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 94 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "eventbus_event_published_count{instance=~\"$system\"} - ignoring(subscriber) group_right eventbus_event_consumed_count{instance=~\"$system\"} or eventbus_event_published_count_total{instance=~\"$system\"} - ignoring(subscriber) group_right eventbus_event_consumed_count_total{instance=~\"$system\"}",
       "legendFormat": "{{instance}} {{channel}} {{subscriber}}"
      }
     ]
    },
    {
     "title": "EL Request Queues",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 94 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "beacon_ee_request_queue_size{instance=~\"$system\"}",
       "legendFormat": "{{instance}} EE Queue Size"
      },
      {
       "expr": "beacon_eth1_request_queue_size{instance=~\"$system\"} or beacon_eth1_request_queue_size_total{instance=~\"$system\"}",
       "legendFormat": "{{instance}} Eth1 Queue Size"
      }
     ]
    },
    {
     "title": "Historic Block Sync",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 94 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "beacon_historical_block_sync_earliest_block{instance=~\"$system\"}",
       "legendFormat": "{{instance}} earliest available block"
      },
      {
       "expr": "-1 * delta(beacon_historical_block_sync_earliest_block{instance=~\"$system\"}[1m])",
       "legendFormat": "{{instance}} Blocks / Minute"
      }
     ]
    },
    {
     "title": "BLS change queue",
     "type": "timeseries",
     "description": "Shows the number of BlsToExecutionChange operations in the operation pool.",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 104 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "beacon_operation_pool_size_SignedBlsToExecutionChangePool{instance=~\"$system\"}",
       "legendFormat": "{{instance}} execution changes"
      },
      {
       "expr": "-1 * delta(beacon_operation_pool_size_SignedBlsToExecutionChangePool{instance=~\"$system\"}[1m])",
       "legendFormat": "{{instance}} execution changes / Minute"
      }
     ]
    }
   ]
  },
  {
   "title": "Block and Blob-Sidecars trackers Pool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 }
  },
  {
   "title": "Pooled Sidecars and Trackers",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 75 },
   "targets": [
    {
     "expr": "beacon_block_blobs_trackers_pool_size{instance=~\"$system\"} or beacon_block_blobs_trackers_pool_size_total{instance=~\"$system\"}",
     "legendFormat": "{{instance}} {{type}}"
    }
   ]
  },
  {
   "title": "Trackers pool stats counters",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 75 },
   "targets": [
    {
     "expr": "rate(beacon_block_blobs_trackers_pool_stats{instance=~\"$system\"}[$__rate_interval]) or rate(beacon_block_blobs_trackers_pool_stats_total{instance=~\"$system\"}[$__rate_interval])",
     "legendFormat": "{{instance}} {{type}} {{subtype}}"
    }
   ]
  },
  {
   "title": "Blobs from EL",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 8, "x": 0, "y": 88 },
   "targets": [
    {
     "expr": "beacon_block_blobs_trackers_pool_stats{instance=~\"$system\", subtype=\"local_el_fetch\", name=\"blob_sidecar\"} or beacon_block_blobs_trackers_pool_stats_total{instance=~\"$system\", subtype=\"local_el_fetch\"}",
     "legendFormat": "{{instance}} Fetched"
    },
    {
     "expr": "beacon_block_blobs_trackers_pool_stats{instance=~\"$system\", subtype=\"local_el\"} or beacon_block_blobs_trackers_pool_stats_total{instance=~\"$system\", subtype=\"local_el\"}",
     "legendFormat": "{{instance}} Received"
    }
   ]
  },
  {
   "title": "Gossip",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 8, "x": 8, "y": 88 },
   "targets": [
    {
     "expr": "beacon_block_blobs_trackers_pool_stats{instance=~\"$system\", subtype=\"gossip\"} or beacon_block_blobs_trackers_pool_stats_total{instance=~\"$system\", subtype=\"gossip\"}",
     "legendFormat": "{{instance}} {{type}}"
    }
   ]
  },
  {
   "title": "Duplicates",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 8, "x": 16, "y": 88 },
   "targets": [
    {
     "expr": "beacon_block_blobs_trackers_pool_stats{instance=~\"$system\", subtype=~\"gossip_duplicate|rpc_duplicate|local_el_duplicate\"} or beacon_block_blobs_trackers_pool_stats_total{instance=~\"$system\", subtype=~\"gossip_duplicate|rpc_duplicate|local_el_duplicate\"}",
     "legendFormat": "{{instance}} {{type}} {{subtype}}"
    }
   ]
  },
  {
   "title": "RPC fetches",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 8, "x": 0, "y": 102 },
   "targets": [
    {
     "expr": "beacon_block_blobs_trackers_pool_stats{instance=~\"$system\", subtype=\"rpc_fetch\"} or beacon_block_blobs_trackers_pool_stats_total{instance=~\"$system\", subtype=\"rpc_fetch\"}",
     "legendFormat": "{{instance}} {{type}}"
    }
   ]
  },
  {
   "title": "RPC receives",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 8, "x": 8, "y": 102 },
   "targets": [
    {
     "expr": "beacon_block_blobs_trackers_pool_stats{instance=~\"$system\", subtype=\"rpc\"} or beacon_block_blobs_trackers_pool_stats_total{instance=~\"$system\", subtype=\"rpc\"}",
     "legendFormat": "{{instance}} {{type}}"
    }
   ]
  }
 ]
}